name: Deploy to Server

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs: 
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install yarn and run unittest
        run: | 
          yarn 
          yarn build
        env:
          CI: true
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: react-github-actions-build
          path: build
  deploy:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Get artifacet
        uses: actions/download-artifact@v3
        with:
          name: react-github-actions-build

      - name: Display structure of downloaded files
        run: ls -R
        # working-directory: react-github-actions-build
